data_path: /scratch/cp3759/thermalizer_data/kolmogorov/ratio10_inc1_diffusion/all.pt
input_channels: 1
output_channels: 1
subsample: -1
save_name: model_weights.pt
dim_mults: [2,4]
base_dim: 32
timesteps: 1000
time_embedding_dim: 256
image_size: 64
noise_sampling_coeff: 0.35
denoise_time: 400
optimization:
  epochs: 120
  batch_size: 64
  lr: 0.005
  wd: 0.05
  scheduler: True
  
