ks:
  L: 22
  N: 128
  dataset_size: 500
  trajectories: 2
  increment: 1
  rollout: 5
  dt: 0.01
  Dt: 0.2
  spinup: 200
  decorr_steps: 200
  test_sims: 10
  test_window: 1000
network:
  arch: CNN
  input_channels: 1
  output_channels: 1
optimization:
  residual: True
  batch_size: 64
  lr: 0.001
  wd: 0.05
  epochs: 10
  scheduler: None
  
