ks:
  L: 22
  N: 128
  dataset_size: 10000
  trajectories: 5
  increment: 50
  rollout: 5
  dt: 0.01
  spinup: 5000
  decorr_steps: 5000
  valid_sims: 10
  valid_window: 5000
network:
  arch: CNN
  input_channels: 1
  output_channels: 1
optimization:
  batch_size: 64
  lr: 0.001
  wd: 0.05
  epochs: 10
  
